### ISSUE TITLE
Hasura - `Connection failure` for events

### ISSUE THREAD

**Issue by mthines** [golevelup/nestjs#538]
Hey.
I'm trying to create events for create/update users but all the events results in errors.

Any suggestions on what I'm doing wrong will be a big help :) 

Thanks!

### Config

```ts
...

@Module({
  imports: [
    HasuraModule.forRoot(HasuraModule, {
      webhookConfig: {
        /**
         * The value of the secret Header. The Hasura module will ensure that incoming webhook payloads contain this
         * value in order to validate that it is a trusted request
         */
        secretFactory: process.env['HASURA_NESTJS_WEBHOOK_SECRET'],
        /** The name of the Header that Hasura will send along with all event payloads */
        secretHeader: 'x-hasura-webhook-secret',
      },
      managedMetaDataConfig: {
        metadataVersion: 'v3',
        dirPath: path.join(process.cwd(), 'hasura/metadata'),
        secretHeaderEnvName: 'HASURA_NESTJS_WEBHOOK_SECRET',
        nestEndpointEnvName: 'NESTJS_EVENT_WEBHOOK_ENDPOINT',
        defaultEventRetryConfig: {
          intervalInSeconds: 15,
          numRetries: 3,
          timeoutInSeconds: 100,
          toleranceSeconds: 21600,
        },
      },
    }),
    AuthModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

### Events
```ts
...

@Injectable()
export class AuthEvents {
  @TrackedHasuraEventHandler({
    triggerName: 'user-updated',
    tableName: 'users',
    definition: { type: 'update', columns: ['email'] },
  })
  handleUserUpdated(evt: HasuraUpdateEvent<User>) {
    console.log(
      'handleUserUpdated was called, due to user.email changing and Hasura sending us a webhook!'
    );
    console.log(
      'email was changed from',
      evt.event.data.old.email,
      'to',
      evt.event.data.new.email
    );
  }
}
```

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/16097850/206429330-22e80d6e-2109-4ac2-afe8-62bd60afe14e.png">

### Event request
```json
{
    "headers": [
        {
            "name": "Content-Type",
            "value": "application/json"
        },
        {
            "name": "User-Agent",
            "value": "hasura-graphql-engine/v2.14.0"
        },
        {
            "name": "x-hasura-webhook-secret",
            "value_from_env": "HASURA_NESTJS_WEBHOOK_SECRET"
        }
    ],
    "payload": {
        "created_at": "2022-12-08T10:52:57.677745Z",
        "delivery_info": {
            "current_retry": 0,
            "max_retries": 3
        },
        "event": {
            "data": {
                "new": {
                    "email": "asdasdfsadffqwe@asd.com",
                    "id": "77c84297-ff84-4e3b-9f4d-d313a1ace3c1",
                    "password": "asdasd"
                },
                "old": {
                    "email": "asdsadffqwe@asd.com",
                    "id": "77c84297-ff84-4e3b-9f4d-d313a1ace3c1",
                    "password": "asdasd"
                }
            },
            "op": "UPDATE",
            "session_variables": {
                "x-hasura-role": "admin"
            },
            "trace_context": {
                "span_id": "1ae731bfaf2e081a",
                "trace_id": "10796892dc33c2e36b507b9eb2731de0"
            }
        },
        "id": "e3824b90-1dca-4f26-83cd-a26f10fad74f",
        "table": {
            "name": "users",
            "schema": "public"
        },
        "trigger": {
            "name": "user-updated"
        }
    },
    "version": "2"
}
```

### Event response
```json
{
    "data": {
        "message": "{\"message\":\"Connection failure\",\"request\":{\"host\":\"localhost\",\"method\":\"POST\",\"path\":\"/api/v1/hasura\",\"port\":3333,\"queryString\":\"\",\"requestHeaders\":{\"Content-Type\":\"application/json\",\"User-Agent\":\"hasura-graphql-engine/v2.14.0\",\"X-B3-ParentSpanId\":\"e7c1a0a6b5f662d5\",\"X-B3-SpanId\":\"257e704acc503a65\",\"X-B3-TraceId\":\"10796892dc33c2e36b507b9eb2731de0\",\"x-hasura-webhook-secret\":\"my-super-secret-key"},\"responseTimeout\":\"ResponseTimeoutMicro 100000000\",\"secure\":false},\"type\":\"http_exception\"}"
    },
    "type": "client_error",
    "version": "2"
}
```

**Comment by WonderPanda** [comment]
How are you running the services locally? Is Hasura running inside of Docker? Where is the Nest app running? I suspect its a networking issue that you shouldn't actually be using this localhost address

**Comment by mthines** [comment]
@WonderPanda thanks for getting back to me.

Yup, the issue was exactly that. The Hasura instance was inside of a Docker container` so I needed to set the env variables accordingly.

Thanks for helping!

#### `.env`

```sh
HASURA_ENDPOINT=http://localhost:8080/v1/graphql
HASURA_GRAPHQL_ADMIN_SECRET=dev-admin-secret
HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgrespassword@postgres:5432/postgres
HASURA_NESTJS_WEBHOOK_SECRET=dev-webhook-secret
JWT_ACCESS_SECRET=dev-jwt-access-secret-which-is-minimum-32-characters-long
NESTJS_EVENT_WEBHOOK_ENDPOINT=http://host.docker.internal:3333/api/v1/hasura/events
```

#### `docker-compose.yml`

```yml
version: '3.6'
services:
  graphql-engine:
    ...
    environment:
      HASURA_GRAPHQL_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL}'
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL}'
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL}'
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_NESTJS_WEBHOOK_SECRET: '${HASURA_NESTJS_WEBHOOK_SECRET}'
      NESTJS_EVENT_WEBHOOK_ENDPOINT: '${NESTJS_EVENT_WEBHOOK_ENDPOINT}'
      HASURA_GRAPHQL_JWT_SECRET: '{ "type": "HS256", "key": "${JWT_ACCESS_SECRET}" }'
volumes:
  db_data:
```
